return {
	settings = {
		pylsp = {
			configurationSources = {'pycodestyle'},
			plugins = {
				flake8 = { enabled = true },	-- Doesn't know about builtin variables
				jedi_completion = {
				  enabled = true,
				  fuzzy = true,
				},
				jedi_definition = { enabled = true },
				jedi_hover = { enabled = true },
				jedi_references = { enabled = true },
				jedi_signature_help = { enabled = true },
				jedi_symbols = { enabled = true },
				jedi_type_definition = { enabled = true },
				pycodestyle = { enabled = true },
				pydocstyle = { enabled = true },
				pyflakes = { enabled = true },
				pylint = {
					enabled = true,
					args = {
						-- These errors/warnings may possibly be generated by pylsp using an
						-- incompatible version of pylint.
						"--disable=unknown-option-value,unrecognized-option",
					},
				},
			},
		},
	},
}
