{ nextcloud }: ''
<?php
$CONFIG = [
	// General
	'instanceid' => 'bamilab777',
	'serverid' => 0,
	'passwordsalt' => getenv('NEXTCLOUD_PASSWORD_SALT'),
	'secret' => getenv('NEXTCLOUD_SECRET'),
	'trusted_domains' => [
		'mesh.local',
		'10.0.0.10',
		'[2001:db8::1]'
	],
	'cookie_domain' => ''',
	'datadirectory' => '/var/nextcloud/data',
	'version' => '${nextcloud.version}',

	// Database
	'dbtype' => 'pgsql',
	'dbhost' => '192.168.0.254',
	'dbname' => 'nextcloud',
	'dbuser' => 'nextcloud',
	'dbpassword' => ''',
	'dbtableprefix' => 'oc_',
	'dbpersistent' => ''',
	'dbreplica' => [
		//['user' => 'nextcloud', 'password' => 'password1', 'host' => 'replica1', 'dbname' => '''],
		//['user' => 'nextcloud', 'password' => 'password2', 'host' => 'replica2', 'dbname' => '''],
	],
	'db.log_request_id' => false,
	'installed' => true,


	'default_language' => 'en',
	'force_language' => false,
	'default_locale' => 'en_US',
	'reduce_to_languages' => [],
	'default_phone_region' => 'BE',
	'force_locale' => false,
	'default_timezone' => 'Europe/Amsterdam',
	'knowledgebaseenabled' => true,
	'knowledgebase.embedded' => false,
	'allow_user_to_change_display_name' => true,
	'skeletondirectory' => '/var/nextcloud/core/skeleton',
	'templatedirectory' => ''',

	'remember_login_cookie_lifetime' => 60 * 60 * 24 * 15,
	'session_lifetime' => 60 * 60 * 24,
	'davstorage.request_timeout' => 30,
	'carddav_sync_request_timeout' => 30,
	'carddav_sync_request_truncation' => 2500,
	'session_relaxed_expiry' => false,
	'session_keepalive' => true,
	'auto_logout' => false,
	'token_auth_enforced' => false,
	'token_auth_activity_update' => 60,
	'auth.bruteforce.protection.enabled' => true,
	'auth.bruteforce.protection.force.database' => false,
	'auth.bruteforce.protection.testing' => false,
	'auth.bruteforce.max-attempts' => 10,
	'ratelimit.protection.enabled' => true,
	'ratelimit_overwrite' => [
		'profile.profilepage.index' => [
			'user' => ['limit' => 300, 'period' => 3600],
			'anon' => ['limit' => 1, 'period' => 300],
		]
	],
	'security.ipv6_normalized_subnet_size' => 56,
	'auth.webauthn.enabled' => true,
	'auth.storeCryptedPassword' => true,
	'hide_login_form' => false,
	'lost_password_link' => 'https://example.org/link/to/password/reset',
	'logo_url' => 'https://example.org',

	'mail_domain' => 'example.com',
	'mail_from_address' => 'nextcloud',
	'mail_smtpdebug' => false,
	'mail_smtpmode' => 'smtp',
	'mail_smtphost' => '127.0.0.1',
	'mail_smtpport' => 25,
	'mail_smtptimeout' => 10,
	'mail_smtpsecure' => ''',
	'mail_smtpauth' => false,
	'mail_smtpname' => ''',
	'mail_smtppassword' => ''',
	'mail_template_class' => '\OC\Mail\EMailTemplate',
	'mail_send_plaintext_only' => false,
	'mail_smtpstreamoptions' => [],
	'mail_sendmailmode' => 'smtp',

	'overwritehost' => ''',
	'overwriteprotocol' => ''',
	'overwritewebroot' => ''',
	'overwritecondaddr' => ''',
	'overwrite.cli.url' => ''',

	'htaccess.RewriteBase' => '/',
	'htaccess.IgnoreFrontController' => false,

	'proxy' => ''',
	'proxyuserpwd' => ''',
	'proxyexclude' => [],

	'allow_local_remote_servers' => true,
	'http_client_add_user_agent_url' => false,
	'trashbin_retention_obligation' => 'auto',
	'versions_retention_obligation' => 'auto',
	'appcodechecker' => true,
	'updatechecker' => true,
	'updater.server.url' => ''',
	'updater.release.channel' => 'stable',
	'has_internet_connection' => false,
	'connectivity_check_domains' => [],
	'check_for_working_wellknown_setup' => true,
	'check_for_working_htaccess' => true,
	'check_data_directory_permissions' => true,
	'config_is_read_only' => true,

	// Logging
	'log_type' => 'syslog',
	'log_type_audit' => 'file',
	'logfile' => '/var/log/nextcloud.log',
	'logfile_audit' => '/var/log/audit.log',
	'logfilemode' => 0640,
	'loglevel' => 1,
	'loglevel_frontend' => 1,
	'loglevel_dirty_database_queries' => 0,
	'syslog_tag' => 'Nextcloud',
	'syslog_tag_audit' => 'Nextcloud',
	'log.condition' => [],
	'log.backtrace' => false,
	'logdateformat' => 'F d, Y H:i:s',
	'logtimezone' => 'Europe/Amsterdam',
	'log_query' => false,
	'log_rotate_size' => 100 * 1024 * 1024,

	// Profiler
	'profiler' => false,
	'profiling.request' => false,
	'profiling.request.rate' => 0.001,
	'profiling.secret' => ''',
	'profiling.sample' => false,
	'profiling.sample.rate' => 1,
	'profiling.sample.rotation' => 60,
	'profiling.path' => '/tmp',

	'activity_expire_days' => 365,
	'activity_use_cached_mountpoints' => false,
	'defaultapp' => 'dashboard,files',
	'appstoreenabled' => false,
	'appstoreurl' => 'https://apps.nextcloud.com/api/v1',
	'appsallowlist' => [],
	'apps_paths' => [
		[
			'path' => '/var/nextcloud/apps',
			'url' => '/apps',
			'writable' => false,
		],
	],
	'enable_previews' => true,
	'preview_concurrency_all' => 8,
	'preview_concurrency_new' => 4,
	'preview_max_x' => 4096,
	'preview_max_y' => 4096,
	'preview_max_filesize_image' => 50,
	'preview_max_memory' => 256,
	'preview_libreoffice_path' => '/usr/bin/libreoffice',
	'preview_ffmpeg_path' => '/usr/bin/ffmpeg',
	'preview_ffprobe_path' => '/usr/bin/ffprobe',
	'preview_imaginary_url' => 'http://previews_hpb:8088/',
	'preview_imaginary_key' => 'secret',
	'enabledPreviewProviders' => [
		'OC\Preview\PNG',
		'OC\Preview\JPEG',
		'OC\Preview\GIF',
		'OC\Preview\BMP',
		'OC\Preview\XBitmap',
		'OC\Preview\Krita',
		'OC\Preview\WebP',
		'OC\Preview\MarkDown',
		'OC\Preview\TXT',
		'OC\Preview\OpenDocument',
	],
	'metadata_max_filesize' => 256,
	'max_file_conversion_filesize' => 100,

	'ldapUserCleanupInterval' => 51,
	'sort_groups_by_name' => false,
	'comments.managerFactory' => '\OC\Comments\ManagerFactory',
	'systemtags.managerFactory' => '\OC\SystemTag\ManagerFactory',
	'maintenance' => false,
	'maintenance_window_start' => 1,
	'ldap_log_file' => ''',
	'openssl' => [],

	// Hashing
	'hashing_default_password' => false,
	'hashingThreads' => PASSWORD_ARGON2_DEFAULT_THREADS,
	'hashingMemoryCost' => PASSWORD_ARGON2_DEFAULT_MEMORY_COST,
	'hashingTimeCost' => PASSWORD_ARGON2_DEFAULT_TIME_COST,
	'hashingCost' => 10,

	// Other
	'dbdriveroptions' => [],
	'pgsql_ssl' => [
		'mode' => ''',
		'cert' => ''',
		'rootcert' => ''',
		'key' => ''',
		'crl' => ''',
	],
	'supportedDatabases' => [
		'pgsql',
	],
	'tempdirectory' => '/tmp/nextcloudtemp',
	'updatedirectory' => ''',
	'forbidden_filenames' => ['.htaccess'],
	'forbidden_filename_basenames' => [],
	'forbidden_filename_characters' => [],
	'forbidden_filename_extensions' => ['.part', '.filepart'],
	'theme' => ''',
	'enforce_theme' => ''',
	'theming.standalone_window.enabled' => true,
	'cipher' => 'AES-256-CTR',
	'encryption.use_legacy_base64_encoding' => false,
	'minimum.supported.desktop.version' => '3.2.50',
	'maximum.supported.desktop.version' => '99.99.99',
	'localstorage.allowsymlinks' => false,
	'localstorage.umask' => 0022,
	'localstorage.unlink_on_truncate' => false,
	'quota_include_external_storage' => false,
	'external_storage.auth_availability_delay' => 1800,
	'files_external_allow_create_new_local' => true,
	'filesystem_check_changes' => 0,
	'part_file_in_storage' => true,
	'filesystem_cache_readonly' => false,
	'trusted_proxies' => [],
	'forwarded_for_headers' => ['HTTP_X_FORWARDED', 'HTTP_FORWARDED_FOR'],
	'allowed_admin_ranges' => ['192.0.2.42/32', '233.252.0.0/24', '2001:db8::13:37/64'],
	'max_filesize_animated_gifs_public_sharing' => 10,
	'filelocking.ttl' => 60 * 60,
	'memcache.locking' => '\\OC\\Memcache\\Redis',
	'filelocking.debug' => false,
	'upgrade.disable-web' => true,
	'upgrade.cli-upgrade-link' => ''',
	'user_ini_additional_lines' => ''',
	'documentation_url.server_logs' => ''',
	'debug' => false,
	'data-fingerprint' => ''',
	'configfilemode' => 0640,
	'copied_sample_config' => true,
	'lookup_server' => 'https://lookup.nextcloud.com',
	'gs.enabled' => false,
	'gs.federation' => 'internal',
	'csrf.optout' => [
		//'/^WebDAVFS/', // OS X Finder
		//'/^Microsoft-WebDAV-MiniRedir/', // Windows WebDAV drive
	],
	'core.login_flow_v2.allowed_user_agents' => [],
	'simpleSignUpLink.shown' => true,
	'login_form_autocomplete' => true,
	'login_form_timeout' => 300,
	'no_unsupported_browser_warning' => false,
	'files_no_background_scan' => false,
	'query_log_file' => ''',
	'query_log_file_requestid' => ''',
	'query_log_file_parameters' => ''',
	'query_log_file_backtrace' => ''',
	'redis_log_file' => ''',
	'diagnostics.logging' => true,
	'diagnostics.logging.threshold' => 0,
	'profile.enabled' => true,
	'account_manager.default_property_scope' => [],
	'projects.enabled' => false,
	'bulkupload.enabled' => true,
	'reference_opengraph' => true,
	'unified_search.enabled' => false,
	'enable_non-accessible_features' => true,
	'binary_search_paths' => [
		'/bin',
	],
	'files.chunked_upload.max_size' => 100 * 1024 * 1024,
	'files.chunked_upload.max_parallel_count' => 5,
	'files.trash.delete' => true,
	'enable_lazy_objects' => true,
	'default_certificates_bundle_path' => \OC::$SERVERROOT . '/resources/config/ca-bundle.crt',
	'preview_expiration_days' => 0,
	'background_jobs_expiration_days' => 60,
];
''
