local odoo_version = require('odoo').find_odoo_version()
local lsp_command = 'pylsp'
if odoo_version ~= nil then
	lsp_command = '/home/therp/wax/' .. odoo_version .. '/wax/venv/bin/pylsp'
end
print("hoyyysynyddysndysnd " .. lsp_command)


return {
  cmd = {lsp_command},
  filetypes = {'python'},
  on_attach = require('autocomplete'),
  settings = {
    pylsp = {
      configurationSources = {'flake8'},
      plugins = {
        flake8 = { enabled = false },	-- Doesn't know about builtin variables
        jedi_completion = {
          enabled = true,
          fuzzy = true,
        },
        jedi_definition = { enabled = true },
        jedi_hover = { enabled = true },
        jedi_references = { enabled = true },
        jedi_signature_help = { enabled = true },
        jedi_symbols = { enabled = true },
        pydocstyle = { enabled = true },
        pyflakes = { enabled = false },	-- Doesn't know about builtin variables
        pylint = {
			enabled = true,
			args = {
				-- These errors/warnings may possibly be generated by pylsp using an incompatible
				-- version of pylint.
				"--disable=unknown-option-value,unrecognized-option",
			},
		},
      }
    }
  },
  root_markers = {'flake.nix', '.git'}
}
