# The Stonenet site is a hugo project.
# Static files will be generated by Hugo, and then served with Nginx.
{ devpkgs, pkgs, ... }:
let
  configFile = pkgs.writers.writeText "nginx.conf" (
    with pkgs;
    ''
      daemon off;
      user nginx;
      error_log /dev/stderr notice;
      worker_processes 1;

      events {}

      http {
        include ${nginx}/conf/mime.types;
        default_type application/octet-stream;

        server {
          listen 8080 default_server;
          server_name _;
          access_log /dev/stderr;

          root /var/www/public; 
          index index.html;

          location / {
            try_files $uri $uri/ =404;
          }
        }
      }
    ''
  );

  prepareFiles = pkgs.runCommand "prepare-files" { } ''
    mkdir -p $out/var/www
    cp -r ${stonenetSiteSrc}/* $out/var/www/
    (
      cd $out/var/www/
      ${pkgs.hugo}/bin/hugo build
    )
  '';

  stonenetSiteSrc = pkgs.fetchFromGitHub {
    owner = "bamidev";
    repo = "stonenet-site";
    rev = "82a1619d238ee9ce550b9840439fa0869e526e16";
    hash = "sha256-yPC26okYNIGSugOCPjcqgYMSQZIor4V2c8MxP4xD49Y=";
    fetchSubmodules = true;
  };
in
pkgs.dockerTools.buildLayeredImage {
  name = "stonenet-site";

  contents = [
    prepareFiles
  ]
  ++ devpkgs;

  fakeRootCommands = ''
    mkdir -p etc tmp var/log/nginx var/www
    chown -R 999:999 var/www
    echo "nginx:x:999:" > etc/group
    echo "nginx:x:999:999:Nginx:/var/empty:/bin/false" > etc/passwd
  '';

  config = {
    Cmd = [
      "${pkgs.nginx}/bin/nginx"
      "-c"
      "${configFile}"
    ];
    ExposedPorts = {
      "8080/tcp" = { };
    };
  };
}
